(function(){
  var soundOn=false;
  var currentLang=localStorage.getItem('japan2026-language')||'ru';
  var videoDays=['0','1','2','4','5','6','7','8','9'];

  var T={
    ru:{
      nav:['маршрут','проводники','условия'],join:'ХОЧУ В ГРУППУ',soundOn:'🔊 ЗВУК: ВКЛ',soundOff:'🔇 ЗВУК: ВЫКЛ',
      heroBadge:'7–15 СЕНТЯБРЯ 2026 • ДО 8 ЧЕЛОВЕК',heroDesc:'9 дней от храмов Токио до самурайской Камакуры, от неона Синдзюку до миров цифрового искусства, от Фудзи до океанских островов',heroBtns:['НАЧАТЬ ПРИКЛЮЧЕНИЕ →','СМОТРЕТЬ ГЛАВЫ ↓'],stats:['дней в Японии','ночей в пути','морских дня','большая вершина'],routeEyebrow:'собираем историю по кадрам',routeTitle:'ГЛАВЫ МАРШРУТА',
      tabs:['0 · ПЕРЕЛЁТ','1 · ТОКИО','2 · КАВАГУЧИКО','★ ФУДЗИ','4 · МЭЙДЗИ','5 · АСАКУСА','6 · TeamLab','7 · ЭНОСИМА','8 · КАМАКУРА','9 · ДОМОЙ'],
      guidesEyebrow:'ваша партия',guidesTitle:'ПРОВОДНИКИ',guideNames:['Андрей Хохлов','Алексей Иванцов'],guideText:['<b>РОЛЬ:</b> альпинист и проводник в неизвестное.<br><b>ОПЫТ:</b> сюгэндо, адаптация и странные истории.','<b>РОЛЬ:</b> мастер маршрута и логистики.<br><b>ОПЫТ:</b> история, география и правильный гедонизм.'],
      includedTitle:'ЧТО ВХОДИТ',included:['Трансферы: аэропорт → размещение → аэропорт','8 ночей, двухместное размещение','Экскурсии, входные билеты и местный транспорт','Турлидер, помощь с визой и авиабилетами'],extraTitle:'ОТДЕЛЬНО',extra:['Авиаперелёт, страховка и питание','Такси и личные активности: лодки, велосипеды','Онсен'],
      inventoryTitle:'ИНВЕНТАРЬ ПУТЕШЕСТВЕННИКА',inventoryHeads:['Для города, экскурсий и пляжа','Для восхождения на Фудзи'],inventoryText:['Летняя одежда, удобная обувь, купальные принадлежности.','Треккинговые ботинки и гамаши, палки, защита от ветра и дождя, пончо, флис или жилет, сменные носки, перчатки, головной убор, очки и крем.'],inventoryNote:'За несколько дней до отъезда сверим прогноз и уточним список для восхождения.',
      requestTitle:'ВАШ КАДР В ЯПОНИИ',requestText:'7–15 сентября 2026. Напишите нам, чтобы получить детали, стоимость и забронировать место в группе.',requestBtn:'ХОЧУ В ГРУППУ →',requestNote:'План может меняться из-за погоды, транспорта, часов работы мест и пожеланий группы.'
    },
    en:{
      nav:['ROUTE','GUIDES','DETAILS'],join:'JOIN THE GROUP',soundOn:'🔊 SOUND: ON',soundOff:'🔇 SOUND: OFF',
      heroBadge:'7–15 SEPTEMBER 2026 • UP TO 8 PEOPLE',heroDesc:'9 days from Tokyo temples to samurai Kamakura, from Shinjuku neon to worlds of digital art, from Fuji to ocean islands',heroBtns:['START THE ADVENTURE →','VIEW THE CHAPTERS ↓'],stats:['days in Japan','nights on the road','days by the sea','great summit'],routeEyebrow:'collecting the story frame by frame',routeTitle:'ITINERARY CHAPTERS',
      tabs:['0 · FLIGHT','1 · TOKYO','2 · KAWAGUCHIKO','★ FUJI','4 · MEIJI','5 · ASAKUSA','6 · TeamLab','7 · ENOSHIMA','8 · KAMAKURA','9 · HOME'],
      guidesEyebrow:'your crew',guidesTitle:'GUIDES',guideNames:['Andrey Khokhlov','Alexey Ivantsov'],guideText:['<b>ROLE:</b> mountaineer and guide into the unknown.<br><b>EXPERIENCE:</b> shugendo, adaptation and unusual stories.','<b>ROLE:</b> route and logistics master.<br><b>EXPERIENCE:</b> history, geography and proper hedonism.'],
      includedTitle:"WHAT'S INCLUDED",included:['Transfers: airport → accommodation → airport','8 nights, double occupancy','Excursions, entry tickets and local transport','Tour leader, help with visas and flight tickets'],extraTitle:'NOT INCLUDED',extra:['Flights, insurance and meals','Taxis and personal activities: boats, bicycles','Onsen'],
      inventoryTitle:"TRAVELER'S KIT",inventoryHeads:['For the city, sightseeing and the beach','For the Mount Fuji ascent'],inventoryText:['Summer clothes, comfortable shoes and swimwear.','Trekking boots and gaiters, poles, wind and rain protection, poncho, fleece or vest, spare socks, gloves, headwear, sunglasses and sunscreen.'],inventoryNote:'A few days before departure, we will check the forecast and confirm the ascent kit list.',
      requestTitle:'YOUR JAPAN FRAME',requestText:'7–15 September 2026. Write to us for details, price and to reserve a place in the group.',requestBtn:'JOIN THE GROUP →',requestNote:"The plan may change due to weather, transport, opening hours and the group's wishes."
    },
    ro:{
      nav:['TRASEU','GHIZI','DETALII'],join:'VREAU ÎN GRUP',soundOn:'🔊 SUNET: PORNIT',soundOff:'🔇 SUNET: OPRIT',
      heroBadge:'7–15 SEPTEMBRIE 2026 • PÂNĂ LA 8 PERSOANE',heroDesc:'9 zile de la templele din Tokyo la Kamakura samurailor, de la neonul din Shinjuku la lumile artei digitale, de la Fuji la insulele oceanului',heroBtns:['ÎNCEPE AVENTURA →','VEZI CAPITOLELE ↓'],stats:['zile în Japonia','nopți în călătorie','zile la mare','un mare vârf'],routeEyebrow:'adunăm povestea cadru cu cadru',routeTitle:'CAPITOLELE ITINERARULUI',
      tabs:['0 · ZBOR','1 · TOKYO','2 · KAWAGUCHIKO','★ FUJI','4 · MEIJI','5 · ASAKUSA','6 · TeamLab','7 · ENOSHIMA','8 · KAMAKURA','9 · ACASĂ'],
      guidesEyebrow:'echipa voastră',guidesTitle:'GHIZI',guideNames:['Andrey Khokhlov','Alexey Ivantsov'],guideText:['<b>ROL:</b> alpinist și ghid spre necunoscut.<br><b>EXPERIENȚĂ:</b> shugendo, adaptare și povești neobișnuite.','<b>ROL:</b> maestru al traseului și logisticii.<br><b>EXPERIENȚĂ:</b> istorie, geografie și hedonism cu gust.'],
      includedTitle:'CE ESTE INCLUS',included:['Transferuri: aeroport → cazare → aeroport','8 nopți, cazare în camere duble','Excursii, bilete de intrare și transport local','Tour leader, ajutor cu viza și biletele de avion'],extraTitle:'SE PLĂTEȘTE SEPARAT',extra:['Zborul, asigurarea și mesele','Taxiuri și activități personale: bărci, biciclete','Onsen'],
      inventoryTitle:'ECHIPAMENTUL CĂLĂTORULUI',inventoryHeads:['Pentru oraș, excursii și plajă','Pentru ascensiunea pe Fuji'],inventoryText:['Haine de vară, încălțăminte comodă și articole pentru plajă.','Bocanci de trekking și ghetre, bețe, protecție de vânt și ploaie, poncho, fleece sau vestă, șosete de schimb, mănuși, acoperământ pentru cap, ochelari și cremă solară.'],inventoryNote:'Cu câteva zile înainte de plecare verificăm prognoza și definitivăm lista pentru ascensiune.',
      requestTitle:'CADRUL VOSTRU DIN JAPONIA',requestText:'7–15 septembrie 2026. Scrieți-ne pentru detalii, preț și rezervarea unui loc în grup.',requestBtn:'VREAU ÎN GRUP →',requestNote:'Planul se poate schimba în funcție de vreme, transport, programul locurilor și dorințele grupului.'
    }
  };

  var cards={
    '0':{ru:['CHAPTER 0 • 6 сентября','ПЕРЕЛЁТ: ПОРТАЛ ОТКРЫТ','Вылет в Японию','День дороги, отдыха и настройки внутреннего компаса на другой часовой пояс.'],en:['CHAPTER 0 • 6 September','FLIGHT: THE PORTAL OPENS','Flight to Japan','A travel day to rest and tune your inner compass to a new time zone.'],ro:['CHAPTER 0 • 6 septembrie','ZBOR: PORTALUL SE DESCHIDE','Zbor spre Japonia','O zi de drum, odihnă și adaptare la un alt fus orar.']},
    '1':{ru:['CHAPTER 1 • 7 сентября','ТОКИО: ПЕРВЫЙ КАДР','Прилёт → заселение → Уэно → Синдзюку','Мягко войдём в ритм Токио: парк Уэно, торговые улочки Амэёко и вечерний Синдзюку с экранами, небоскрёбами и 3D-котом.'],en:['CHAPTER 1 • 7 September','TOKYO: THE FIRST FRAME','Arrival → check-in → Ueno → Shinjuku','Ease into Tokyo: Ueno Park, Ameyoko shopping streets and evening Shinjuku with screens, skyscrapers and its 3D cat.'],ro:['CHAPTER 1 • 7 septembrie','TOKYO: PRIMUL CADRU','Sosire → cazare → Ueno → Shinjuku','Intrăm ușor în ritmul Tokyo: parcul Ueno, străduțele Ameyoko și Shinjuku de seară cu ecrane, zgârie-nori și pisica 3D.']},
    '2':{ru:['CHAPTER 2 • 8 сентября','ФУДЗИ И КАВАГУЧИКО','Токио → район Фудзи → озеро Кавагучико','Открыточные виды из Oishi Park, прогулка у озера, опциональная лодка и музей кукол Юки Атаэ. Ночуем у Фудзи.'],en:['CHAPTER 2 • 8 September','FUJI AND KAWAGUCHIKO','Tokyo → Fuji area → Lake Kawaguchiko','Postcard views from Oishi Park, a lakeside walk, an optional boat ride and the Yuki Atae Doll Museum. Overnight near Fuji.'],ro:['CHAPTER 2 • 8 septembrie','FUJI ȘI KAWAGUCHIKO','Tokyo → zona Fuji → lacul Kawaguchiko','Priveliști de carte poștală din Oishi Park, plimbare pe lângă lac, barcă opțională și muzeul păpușilor Yuki Atae. Dormim lângă Fuji.']},
    '3':{ru:['SPECIAL CHAPTER • 9 сентября','ВОСХОЖДЕНИЕ НА ФУДЗИ','ИДЕМ К ВЕРШИНЕ!','Ранний выход на маршрут Yoshida, восхождение, встреча рассвета над облаками и возвращение в Кавагучико. Маршрут проходит при подходящей погоде и открытой трассе, с соблюдением официальных правил.','После возвращения: отдых и восстановление в традиционном японском доме в Кавагучико.'],en:['SPECIAL CHAPTER • 9 September','ASCENT OF MOUNT FUJI','WE CLIMB TO THE SUMMIT!','Early start on the Yoshida Trail, ascent, sunrise above the clouds and return to Kawaguchiko. The route is taken only in suitable weather, on an open trail and under the official rules.','After the return: rest and recovery in a traditional Japanese house in Kawaguchiko.'],ro:['SPECIAL CHAPTER • 9 septembrie','ASCENSIUNEA PE FUJI','URCĂM SPRE VÂRF!','Pornire devreme pe traseul Yoshida, ascensiune, răsărit deasupra norilor și întoarcere în Kawaguchiko. Parcurgem traseul doar pe vreme potrivită, când ruta este deschisă și conform regulilor oficiale.','După întoarcere: odihnă și recuperare într-o casă japoneză tradițională din Kawaguchiko.']},
    '4':{ru:['CHAPTER 4 • 10 сентября','ТОКИО: ТИШИНА И НЕОН','Кавагучико → Токио → Мэйдзи → Акихабара','Лесное святилище Мэйдзи рядом с Харадзюку, затем Акихабара: электроника, игры, манга и ночные вывески.'],en:['CHAPTER 4 • 10 September','TOKYO: QUIET AND NEON','Kawaguchiko → Tokyo → Meiji → Akihabara','Forest-shaded Meiji Shrine near Harajuku, then Akihabara: electronics, games, manga and neon signs.'],ro:['CHAPTER 4 • 10 septembrie','TOKYO: LINIȘTE ȘI NEON','Kawaguchiko → Tokyo → Meiji → Akihabara','Sanctuarul Meiji lângă Harajuku, apoi Akihabara: electronică, jocuri, manga și reclame de noapte.']},
    '5':{ru:['CHAPTER 5 • 11 сентября','СТАРЫЙ ТОКИО / НОВЫЙ ТОКИО','Асакуса → Skytree → Сибуя → Гинза','Сэнсодзи и Nakamise-dori, вид с Tokyo Skytree, диагональный перекрёсток Сибуи и элегантная вечерняя Гинза.'],en:['CHAPTER 5 • 11 September','OLD TOKYO / NEW TOKYO','Asakusa → Skytree → Shibuya → Ginza','Senso-ji and Nakamise-dori, Tokyo Skytree views, Shibuya Crossing and elegant evening Ginza.'],ro:['CHAPTER 5 • 11 septembrie','TOKYO VECHI / TOKYO NOU','Asakusa → Skytree → Shibuya → Ginza','Senso-ji și Nakamise-dori, priveliștea din Tokyo Skytree, intersecția Shibuya și eleganta Ginza de seară.']},
    '6':{ru:['CHAPTER 6 • 12 сентября','БУДУЩЕЕ У ЗАЛИВА','TeamLab → Toyosu → Odaiba → Miraikan','Цифровое искусство TeamLab, свежая рыба в Toyosu Senkyaku Banrai, футуристическая Одайба и Geo-Cosmos в музее будущего. Вечером по желанию: онсен Tokyo Toyosu Manyo Club.'],en:['CHAPTER 6 • 12 September','THE FUTURE BY THE BAY','TeamLab → Toyosu → Odaiba → Miraikan','TeamLab digital art, fresh fish at Toyosu Senkyaku Banrai, futuristic Odaiba and Geo-Cosmos at the Museum of the Future. Optional evening: Tokyo Toyosu Manyo Club onsen.'],ro:['CHAPTER 6 • 12 septembrie','VIITORUL LÂNGĂ GOLF','TeamLab → Toyosu → Odaiba → Miraikan','Arta digitală TeamLab, pește proaspăt la Toyosu Senkyaku Banrai, Odaiba futuristă și Geo-Cosmos la muzeul viitorului. Seara, opțional: onsen Tokyo Toyosu Manyo Club.']},
    '7':{ru:['CHAPTER 7 • 13 сентября','ЭНОСИМА: ОСТРОВ ДРАКОНА','Токио → Fujisawa → Enoshima → Hase','Легендарный поезд Enoden, пляж, мост на остров, святилища Бэнтэн, Sea Candle, пещеры Iwaya и shirasu-don. К вечеру заселяемся в тихий Hase у моря.'],en:['CHAPTER 7 • 13 September','ENOSHIMA: DRAGON ISLAND','Tokyo → Fujisawa → Enoshima → Hase','The legendary Enoden train, beach, island bridge, Benzaiten shrines, Sea Candle, Iwaya caves and shirasu-don. By evening, we settle into quiet Hase by the sea.'],ro:['CHAPTER 7 • 13 septembrie','ENOSHIMA: INSULA DRAGONULUI','Tokyo → Fujisawa → Enoshima → Hase','Trenul legendar Enoden, plaja, podul spre insulă, sanctuarele Benzaiten, Sea Candle, peșterile Iwaya și shirasu-don. Spre seară ne cazăm în Hase, lângă mare.']},
    '8':{ru:['CHAPTER 8 • 14 сентября','КАМАКУРА: БУДДА И МОРЕ','Hase → Kamakura → Ōfuna → Hase','Великий Будда, Hase-dera, Komachi-dori, Hachimangu, бамбук Hokokuji и белая Ōfuna Kannon. Затем несколько часов у Yuigahama и прощальный вечер.'],en:['CHAPTER 8 • 14 September','KAMAKURA: BUDDHA AND SEA','Hase → Kamakura → Ōfuna → Hase','Great Buddha, Hase-dera, Komachi-dori, Hachimangu, Hokokuji bamboo grove and white Ōfuna Kannon. Then a few hours at Yuigahama and a farewell evening.'],ro:['CHAPTER 8 • 14 septembrie','KAMAKURA: BUDDHA ȘI MAREA','Hase → Kamakura → Ōfuna → Hase','Marele Buddha, Hase-dera, Komachi-dori, Hachimangu, pădurea de bambus Hokokuji și statuia albă Ōfuna Kannon. Apoi câteva ore la Yuigahama și o seară de rămas-bun.']},
    '9':{ru:['FINAL CHAPTER • 15 сентября','ДОМОЙ, С ПОЛНЫМ ЧЕМОДАНОМ ПОДАРКОВ И ВПЕЧАТЛЕНИЙ','Hase / Kamakura → Yokohama → Haneda','Ранний выезд через Йокогаму, запас на регистрацию, последние покупки и вылет домой.'],en:['FINAL CHAPTER • 15 September','HOME, WITH A SUITCASE FULL OF GIFTS AND MEMORIES','Hase / Kamakura → Yokohama → Haneda','Early departure via Yokohama, time for check-in, last shopping and the flight home.'],ro:['FINAL CHAPTER • 15 septembrie','ACASĂ, CU O VALIZĂ PLINĂ DE CADOURI ȘI AMINTIRI','Hase / Kamakura → Yokohama → Haneda','Plecare devreme prin Yokohama, timp pentru check-in, ultimele cumpărături și zborul spre casă.']}
  };

  function setText(el,text){if(el)el.textContent=text;}
  function setList(nodes,arr){nodes.forEach(function(el,i){if(arr[i]!==undefined)el.textContent=arr[i];});}

  function installVideos(){
    videoDays.forEach(function(day){
      var ch=document.querySelector('.chapter[data-chapter="'+day+'"]');if(!ch)return;
      var panel=ch.querySelector('.panel-grid > div:last-child');if(!panel)return;
      panel.style.padding='0';panel.style.overflow='hidden';
      panel.innerHTML='<video muted loop playsinline controls preload="metadata" style="display:block;width:100%;height:auto;aspect-ratio:16/9;object-fit:contain;background:#000"><source src="assets/day-'+day+'-v2.mp4?v=9" type="video/mp4"><source src="assets/day-'+day+'.mp4?v=9" type="video/mp4"></video>';
    });
  }

  function syncMedia(){
    document.querySelectorAll('.chapter video').forEach(function(v){var ch=v.closest('.chapter'),active=ch&&!ch.hidden;if(active){v.muted=!soundOn;v.volume=1;try{var p=v.play();if(p&&p.catch)p.catch(function(){});}catch(e){}}else{v.muted=true;try{v.pause();}catch(e){}}});
    var b=document.getElementById('site-sound-toggle');if(b){b.style.display='';b.textContent=soundOn?T[currentLang].soundOn:T[currentLang].soundOff;b.setAttribute('aria-pressed',String(soundOn));}
  }

  function translateCard(day,lang){
    var ch=document.querySelector('.chapter[data-chapter="'+day+'"]'),t=cards[day]&&cards[day][lang];if(!ch||!t)return;
    setText(ch.querySelector(':scope > p.display'),t[0]);setText(ch.querySelector(':scope > h3'),t[1]);
    if(day==='3'){
      var sp=ch.querySelector('.border-red-500');if(sp){var tt=sp.querySelector('p.display');if(tt){tt.childNodes[0].nodeValue=t[2];var span=tt.querySelector('span');if(span)span.textContent='3 776 M';}setText(sp.querySelector('p.mt-3'),t[3]);}setText(ch.querySelector(':scope > p.mt-5'),t[4]);
    }else{var first=ch.querySelector('.panel-grid > div:first-child');if(first){setText(first.querySelector('b'),t[2]);setText(first.querySelector('p'),t[3]);}}
  }

  function translateStatic(lang){
    var t=T[lang];
    setList(document.querySelectorAll('header nav a'),t.nav);setText(document.querySelector('header a[href="#request"]'),t.join);
    setText(document.querySelector('.hero .comic-thin.bg-black'),t.heroBadge);setText(document.querySelector('.hero p.mt-7'),t.heroDesc);setList(document.querySelectorAll('.hero .mt-8 a'),t.heroBtns);
    setList(document.querySelectorAll('main > section:nth-of-type(2) b'),t.stats);setText(document.querySelector('#route .marker'),t.routeEyebrow);setText(document.querySelector('#route h2.display'),t.routeTitle);
    var tabs=document.querySelectorAll('.day-tab');tabs.forEach(function(x,i){x.textContent=t.tabs[i];x.dataset.day=String(i);});
    setText(document.querySelector('#guides > p.marker'),t.guidesEyebrow);setText(document.querySelector('#guides > h2'),t.guidesTitle);
    var ga=document.querySelectorAll('#guides article');ga.forEach(function(a,i){setText(a.querySelector('h3'),t.guideNames[i]);var p=a.querySelector('p.mt-2');if(p)p.innerHTML=t.guideText[i];});
    var inc=document.querySelectorAll('#included > div > div');if(inc[0]){setText(inc[0].querySelector('h2'),t.includedTitle);setList(inc[0].querySelectorAll('li'),t.included);}if(inc[1]){setText(inc[1].querySelector('h2'),t.extraTitle);setList(inc[1].querySelectorAll('li'),t.extra);}
    var inv=document.querySelector('#included + section .comic');if(inv){setText(inv.querySelector('h2'),t.inventoryTitle);setList(inv.querySelectorAll('.grid > div > b'),t.inventoryHeads);setList(inv.querySelectorAll('.grid > div > p'),t.inventoryText);setText(inv.querySelector(':scope > p.mt-5'),t.inventoryNote);}
    var req=document.querySelector('#request');if(req){setText(req.querySelector('h2'),t.requestTitle);setText(req.querySelector('p.mt-5'),t.requestText);setText(req.querySelector('a'),t.requestBtn);var ps=req.querySelectorAll('p');if(ps.length>1)setText(ps[ps.length-1],t.requestNote);}
    document.querySelectorAll('[data-site-lang]').forEach(function(b){var active=b.dataset.siteLang===lang;b.style.display='';b.classList.toggle('bg-black',active);b.classList.toggle('text-white',active);b.classList.toggle('bg-white',!active);});
  }

  function updateChapterLabel(day){var label=document.getElementById('chapter-label');if(!label)return;var tx=T[currentLang].tabs[Number(day)]||'';var prefix=currentLang==='ru'?'ДЕНЬ ':currentLang==='ro'?'ZIUA ':'DAY ';label.textContent=prefix+tx.replace('★ ','');}

  function applyLanguage(lang){currentLang=lang;localStorage.setItem('japan2026-language',lang);document.documentElement.lang=lang;translateStatic(lang);document.querySelectorAll('.chapter[data-chapter]').forEach(function(ch){translateCard(ch.dataset.chapter,lang);});var active=document.querySelector('.day-tab[aria-selected="true"]')||document.querySelector('.day-tab');if(active)updateChapterLabel(active.dataset.day||'0');syncMedia();}

  function activateChapter(day,button){day=String(day);document.querySelectorAll('.chapter[data-chapter]').forEach(function(ch){ch.hidden=ch.dataset.chapter!==day;});document.querySelectorAll('.day-tab').forEach(function(tab){tab.setAttribute('aria-selected','false');tab.classList.remove('red');});if(button){button.setAttribute('aria-selected','true');if(day==='3')button.classList.add('red');}updateChapterLabel(day);syncMedia();}

  function bind(){document.querySelectorAll('.day-tab').forEach(function(button,i){button.dataset.day=String(i);button.onclick=function(e){if(e)e.preventDefault();activateChapter(button.dataset.day,button);return false;};});var sound=document.getElementById('site-sound-toggle');if(sound){sound.style.display='';sound.onclick=function(e){if(e)e.preventDefault();soundOn=!soundOn;syncMedia();return false;};}document.querySelectorAll('[data-site-lang]').forEach(function(button){button.style.display='';button.onclick=function(e){if(e)e.preventDefault();applyLanguage(button.dataset.siteLang);return false;};});}

  function boot(){installVideos();bind();applyLanguage(currentLang);window.showChapter=activateChapter;var active=document.querySelector('.day-tab[aria-selected="true"]')||document.querySelector('.day-tab');if(active)activateChapter(active.dataset.day||'0',active);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();